VAR_NAME = 'var_name'
STD_NAME = 'standard_name'
DATA_TYPE = 'column_type'
CONVERSION_TO_BE_APPLIED = 'conversion_to_be_applied'
NOMENCLATURE_TO_BE_APPLIED = 'nomenclature_to_be_applied'
STRING_CLEANING_TO_BE_APPLIED = 'space_cleaning_to_be_applied'

MYCOLUMN = "myColumn type"
CLMN_INPUT = 'clmn Input'
CLMN_INPUT_STR = 'input strategy'
CLMN_MULTIPLIER = 'multiplier'
VAR_NAME_CLMN = 'mariable name'
STANDARD_NAME_CLMN = 'standard name'

DATASET_NAME = 'dataset name'
DIRECTORY = 'directory'
COLUMN_LIST = 'column list'
BASE_DATASET_TIMESTAMP = 'base dataset timestamp'
SOURCE_NAME = 'source name'
SOURCE_TIMESTAMP = 'source timestamp'
TO_BE_TRANSPOSED = 'to be transposed'
USE_COLS = 'use cols'
SKIP_ROW_BF_HEADER = 'skip row bf header'
SKIP_ROW_AF_HEADER = 'skip row af header'
ENCODING = 'encoding'
INDEX_COL = 'index col'
DECIMAL = 'decimal'
MYCOLUMN_DICT_LIST = 'my column dict list'

FOLDER = 'folder'
FILE = 'file'
FORMAT = 'format'
SHEET = 'sheet'
