name = 'name'
my_timestamp = 'timestamp'
bf_header = 'bf header'
af_header = 'af header'

filepath = 'filepath'
sheet = 'sheet'
df_setup_clmn_filepath = 'df setup clmn filepath'
format = 'format'
source_dict = 'source dict'
to_be_transposed = 'to be transposed'
use_cols = 'use cols'
skip_row = 'skip row'
encoding = 'encoding'
decimal = 'decimal'
nrows = 'nrows'
date_parser = 'date parser'

old_uom = 'old uom'
new_uom = 'new uom'
any_mtx_conversion = 'any_mtx_conversion'

setup_filepath = 'setup_filepath'
setup_raw_sheet_name = 'setup_raw_sheet_name'
setup_mtx_sheet_name = 'setup_mtx_sheet_name'
column_sheet_name = 'column_sheet_name'
root_folder = 'root_folder'
json_folder = 'json_folder'
dataframe_folder = 'dataframe_folder'
archive_folder = 'archive_folder'
df_setup_folder = 'df_setup_folder'
df_error_folder = 'df_error_folder'
index_col = 'index_col'
