name = 'name'
my_timestamp = 'timestamp'
bf_header = 'bf header'
af_header = 'af header'

filepath = 'filepath'
sheet = 'sheet'
df_setup_clmn_filepath = 'df setup clmn filepath'
format = 'format'
source_dict = 'source dict'
to_be_transposed = 'to be transposed'
use_cols = 'use cols'
skip_row = 'skip row'
encoding = 'encoding'
decimal = 'decimal'
nrows = 'nrows'
date_parser = 'date parser'

old_uom = 'old uom'
new_uom = 'new uom'
any_mtx_conversion = 'any_mtx_conversion'
