void = 'void'
uom_general = 'general'
uom_specific = 'specific'
csv = 'csv'
json = 'json'
json_indent = 4
header = 0
index_col = None
usecols = 'A:AZ'
skiprows = 0
nan_filler_for_non_numeric = ''
nan_filler_for_numeric = 0
row_main = 'Main'
row_input = 'Input'
row_input_strategy = 'Input strategy'
row_multiplier = 'Multiplier'
row_nan_handling_strategy = 'NAN handling strategy'
encoding_to_save = 'utf_32'
date_parser_to_save = '%m/%d/%Y'
split_char = ' ^*^ '
not_applicable = 'Not applicable'
folder_separator = '/'
