spreadsheet_clmn_names = 'Spreadsheet clmn names'
spreadsheet_clmn_position = 'Spreadsheet clmn position'
spreadsheet_row_names = 'Spreadsheet row names'
spreadsheet_row_position = 'Spreadsheet row position'
fill_with_constant = 'Fill with constant'
fill_with_range_1_to_12 = 'Fill with range [1 - 12]'