is_forecast = 'is_forecast'

new = 'new'
original = 'original'

term_before_nomenclature = 'term_before_nomenclature'
term_after_nomenclature = 'term_after_nomenclature'
error = 'error'

volume = 'volume'
volume_list = ['volume_a', 'volume_b', 'volume_c', 'volume_d', 'volume_e']
date = 'date'
initial_date = 'initial_date'
end_date = 'end_date'
month_day_as_date = 'month_day_as_date'
period = 'period'
fiscal_year = 'fiscal_year'
multiplier = 'multiplier'
part_number_code = 'part_number_code'
part_number_description = 'part_number_description'
strategy = 'strategy'
si_uom = 'si_uom'
uom = 'uom'
distance_uom = 'distance_uom'
weight_uom = 'weight_uom'
distance = 'distance'
weight = 'weight'
volume_uom = 'volume_uom'
business_unit = 'business_unit'
distance_si_uom = 'distance_si_uom'
weight_si_uom = 'weight_si_uom'
volume_si_uom = 'volume_si_uom'

location_l0 = 'location_l0'
vendor_code = 'vendor_code'
category = 'category'
part_number_uom = 'part_number_uom'
activity_code = 'activity_code'
# yield_activity = 'yield_activity'
part_number_si_uom = 'part_number_si_uom'
activity_uom = 'activity_uom'
activity_usage = 'activity_usage'

clmn_var_name = 'clmn_var_name'
clmn_rep_name = 'clmn_rep_name'
my_type = 'my_type'
uom_conversion_to_be_applied = 'uom_conversion_to_be_applied'
nomenclature_to_be_applied = 'nomenclature_to_be_applied'
string_cleaning_to_be_applied = 'string_cleaning_to_be_applied'
source_name = 'source_name'
source_last_update = 'source_last_update'
timestamp = 'timestamp'

budget = 'budget'
budget_strategy = 'budget_strategy'
description = 'description'
bank = 'bank'
account_type = 'account_type'